name: goalquest
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter


  google_fonts: ^6.3.2
  supabase_flutter: ^2.5.6
  cupertino_icons: ^1.0.8
  flutter_map: ^8.2.2
  flutter_riverpod: ^2.0.0
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  image_picker: ^1.2.1
  app_links: ^6.4.1
  permission_handler: ^12.0.1
  flutter_launcher_icons: ^0.13.1

  #firebase_core: ^2.0.0
  #firebase_auth: ^4.0.0
 # cloud_firestore: ^4.0.0
  #firebase_storage: ^11.0.0
  #firebase_analytics: ^10.0.0
  #firebase_messaging: ^14.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/"
  min_sdk_android: 21

